name: CI

on:
  push:
    branches:
      - 'main'
      - 'master'
      - 'dev'
      - 'feature-*'
      - 'fix-*'
      - 'hotfix-*'
      - 'refactor-*'

jobs:
  publish-npm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
          registry-url: https://registry.npmjs.org/
      - run: yarn install
      - run: yarn test
      - run: yarn build
      - run: npm config get registry
